// Aircraft Overhead Display -- production firmware for the Waveshare
// ESP32-S3-RGB-Matrix board driving a 64x64 HUB75 panel.
//
// Only run this AFTER the WiFi HTTP Text Display firmware
// (matrix64/02_http_display) is confirmed working -- same panel config,
// same double-buffer/flip pattern, this just adds SD icon loading and a
// richer JSON payload/layout on top.
//
// SD card handling: Waveshare's own 05_AnimatedGIFPanel_SD example flags
// (in a code comment) that the TF card becomes unreliable once the HUB75
// DMA display is running. So instead of reading icon files from SD on
// each request, every icon under /icons on the SD card is preloaded into
// PSRAM once at boot, BEFORE the matrix DMA starts -- the SD card is never
// touched again after setup(). SD card must be FAT32.
//
// Icon files: 24x24 raw RGB565, no header, 1152 bytes each, named
// <name>.bin (e.g. /icons/sq_logo.bin) -- generated by:
//   python3 tools/convert_tiles.py --input logos/ --size 24 --format raw565 --output icons
// then copy icons/*.bin to /icons/ on the SD card (not the raw tailfin/
// source images -- those are full-size .webp/.png, not decodable on-device).
//
// Payload from matrix64_aircraft_workflow.json's Build Payload node:
//   {
//     "flight": "SQ123", "airline": "Singapore Airlines",
//     "altitudeFt": 35000,
//     "originCode": "SIN", "destCode": "KUL",
//     "originCity": "Singapore Changi Airport",
//     "destCity": "Kuala Lumpur International Airport",
//     "icon": "sq_logo", "make": "Airbus", "modelShort": "A388"
//   }
//
// Rendering: everything is drawn into an off-screen GFXcanvas16 (same
// draw calls as the real panel -- setCursor/print/drawRGBBitmap all work
// on it identically), then blitted onto the physical display each frame.
// This also means the exact same frame can be served over HTTP as a BMP
// for debugging (see /debug/screenshot.bmp below) instead of needing to
// photograph the panel.
//
// Scroll policy: every line scrolls ONLY if it doesn't fit its available
// width statically (see scrollIfNeeded() below) -- except the city-name
// line, which always scrolls (full airport names routinely exceed 64px
// even alone, so there's no meaningful "fits" case for it).
//
//  y  0- 7: airline name, full width, e.g. "Singapore Airlines"
//  y  8-15: flight number + altitude, full width, e.g. "SQ123   35000ft"
//  y 16-39: icon (24x24, left-aligned) with, to its right:
//             y ~20: make (manufacturer), e.g. "Airbus"
//             y ~30: modelShort (short ICAO type code), e.g. "A320"
//           (airframe age would go here too, but no data source has it --
//           adsbdb's /v0/aircraft/{icao24} has no build-date field)
//  y 41-48: IATA route codes, full width, e.g. "SIN>KUL"
//  y 49-56: origin -> destination city names (ALWAYS scrolling)
//
// Libraries required (Arduino Library Manager):
//   - "ESP32 HUB75 LED MATRIX PANEL DMA Display" by mrfaptastic
//   - "ArduinoJson" by Benoit Blanchon
// (WebServer.h, FS.h, SD_MMC.h all ship with the esp32 core -- no install)
//
// Copy secrets.h.example to secrets.h and fill in your WiFi credentials
// before building -- secrets.h is gitignored, never commit real creds.

#include <WiFi.h>
#include <WebServer.h>
#include <ArduinoJson.h>
#include <ESP32-HUB75-MatrixPanel-I2S-DMA.h>
#include <Adafruit_GFX.h>
#include <time.h>
#include "FS.h"
#include "SD_MMC.h"
#include "secrets.h"

// Timezone offset from UTC in seconds (edit per location). Default here is
// IST (UTC+5:30) to match the HOME_LAT/HOME_LON in matrix64_aircraft_workflow.json.
#define TIMEZONE_OFFSET_SEC 19800
#define DAYLIGHT_OFFSET_SEC 0

#define PANEL_RES_X 64
#define PANEL_RES_Y 64
#define PANEL_CHAIN 1

// 0 = no rotation, 1 = 90 deg, 2 = 180 deg, 3 = 270 deg
#define DISPLAY_ROTATION 0

// SD_MMC 1-bit GPIO mapping for this exact board, from Waveshare's own
// 05_AnimatedGIFPanel_SD example -- not guessed.
#define BSP_SD_D0  17
#define BSP_SD_CMD 44
#define BSP_SD_CLK 1

#define ICON_SIZE 24
#define MAX_ICONS 300

// Layout constants (see header comment above for the row map)
#define AIRLINE_Y 0
#define FLIGHTALT_Y 8
#define ICON_Y 16
#define ICON_X 0
#define RIGHT_COL_X (ICON_SIZE + 2)
#define MAKE_Y (ICON_Y + 4)
#define MODELSHORT_Y (ICON_Y + 14)
#define IATA_Y (ICON_Y + ICON_SIZE + 1)  // 41
#define CITY_Y (IATA_Y + 8)              // 49

#define FULL_WIDTH_AVAIL (PANEL_RES_X - 2)     // full-width rows, 1px margin each side
#define RIGHT_COL_AVAIL (PANEL_RES_X - RIGHT_COL_X - 1) // beside-icon rows

struct IconEntry {
  String name;      // filename without extension, e.g. "sq_logo"
  uint16_t *pixels;  // ICON_SIZE*ICON_SIZE RGB565, PSRAM-allocated
};

IconEntry icons[MAX_ICONS];
int iconCount = 0;

MatrixPanel_I2S_DMA *dma_display = nullptr;
GFXcanvas16 canvas(PANEL_RES_X, PANEL_RES_Y);
// Scratch canvas for the beside-icon column (make/modelShort): scrolling
// long text (e.g. "Avions de Transport Régional" for ATR) is drawn into
// this narrower buffer first, then blitted -- so it can never sweep across
// the icon area the way a full-width scroll would.
GFXcanvas16 rightColCanvas(RIGHT_COL_AVAIL, 8);
WebServer server(80);
uint16_t textColor;

String currentIcon = "";

// Conditionally-scrolling lines: static if they fit their row's available
// width, scroll only if they don't. Each needs its own scrollX so an
// in-progress scroll doesn't reset just because another line redraws.
String lineAirline = "";
String lineFlightAlt = "";
String lineMake = "";
String lineModelShort = "";
String lineIata = "";
int scrollXAirline = PANEL_RES_X;
int scrollXFlightAlt = PANEL_RES_X;
int scrollXMake = PANEL_RES_X;
int scrollXModelShort = PANEL_RES_X;
int scrollXIata = PANEL_RES_X;

// Always-scrolling line (city names)
String lineCity = "";
int scrollXCity = PANEL_RES_X;

unsigned long lastScroll = 0;

uint16_t *findIcon(const String &name) {
  for (int i = 0; i < iconCount; i++) {
    if (icons[i].name == name) return icons[i].pixels;
  }
  return nullptr;
}

void preloadIcons() {
  File dir = SD_MMC.open("/icons");
  if (!dir || !dir.isDirectory()) {
    Serial.println("No /icons directory found on SD card -- icons will be blank");
    return;
  }

  const size_t expectedBytes = ICON_SIZE * ICON_SIZE * 2;
  File f = dir.openNextFile();
  while (f && iconCount < MAX_ICONS) {
    if (!f.isDirectory()) {
      String fname = String(f.name());
      int slash = fname.lastIndexOf('/');
      if (slash >= 0) fname = fname.substring(slash + 1);
      if (fname.endsWith(".bin")) {
        if (f.size() == (int)expectedBytes) {
          uint16_t *buf = (uint16_t *)ps_malloc(expectedBytes);
          if (buf) {
            f.read((uint8_t *)buf, expectedBytes);
            icons[iconCount].name = fname.substring(0, fname.length() - 4); // strip ".bin"
            icons[iconCount].pixels = buf;
            iconCount++;
          } else {
            Serial.printf("PSRAM alloc failed for %s\n", fname.c_str());
          }
        } else {
          Serial.printf("Skipping %s: %d bytes, expected %d (not a %dx%d raw565 icon)\n",
                         fname.c_str(), (int)f.size(), (int)expectedBytes, ICON_SIZE, ICON_SIZE);
        }
      }
    }
    f = dir.openNextFile();
  }
  Serial.printf("Preloaded %d icons from SD into PSRAM\n", iconCount);
}

void setupSD() {
  if (!SD_MMC.setPins(BSP_SD_CLK, BSP_SD_CMD, BSP_SD_D0)) {
    Serial.println("SD_MMC setPins failed");
    return;
  }
  if (!SD_MMC.begin("/sdcard", true)) {
    Serial.println("SD card mount failed (is it FAT32?)");
    return;
  }
  if (SD_MMC.cardType() == CARD_NONE) {
    Serial.println("No SD card detected");
    return;
  }
  preloadIcons();
}

void setupMatrix() {
  HUB75_I2S_CFG mxconfig(PANEL_RES_X, PANEL_RES_Y, PANEL_CHAIN);
  // Confirmed working config for this board+panel -- see matrix64/02_http_display
  // for how this was arrived at (gpio.e is the row-address line; without it,
  // content straddling the row-32 boundary splits into two bands).
  mxconfig.gpio.e = 9;
  mxconfig.clkphase = false;
  mxconfig.driver = HUB75_I2S_CFG::FM6126A;
  mxconfig.double_buff = true;

  dma_display = new MatrixPanel_I2S_DMA(mxconfig);
  dma_display->begin();
  dma_display->setRotation(DISPLAY_ROTATION);
  dma_display->setBrightness8(60);
  dma_display->clearScreen();
  textColor = 0xFFFF; // white, RGB565
}

void setupWiFi() {
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.printf("Connecting to %s", WIFI_SSID);
  while (WiFi.status() != WL_CONNECTED) {
    delay(300);
    Serial.print(".");
  }
  Serial.printf("\nConnected. IP: %s\n", WiFi.localIP().toString().c_str());

  lineCity = "READY " + WiFi.localIP().toString();
  scrollXCity = PANEL_RES_X;
}

// Called once at boot, after WiFi is up. NTP sync happens in the background;
// the clock screen (drawClock) just shows "SYNCING..." until getLocalTime()
// first succeeds, so we don't need to block setup() waiting for it.
void setupNTP() {
  configTime(TIMEZONE_OFFSET_SEC, DAYLIGHT_OFFSET_SEC, "pool.ntp.org", "time.nist.gov");
  Serial.println("NTP configured");
}

void resetAllScrollPositions() {
  scrollXAirline = PANEL_RES_X;
  scrollXFlightAlt = PANEL_RES_X;
  // These two scroll within the narrower rightColCanvas, not the full
  // panel, so they should re-enter from just off ITS right edge.
  scrollXMake = RIGHT_COL_AVAIL;
  scrollXModelShort = RIGHT_COL_AVAIL;
  scrollXIata = PANEL_RES_X;
  scrollXCity = PANEL_RES_X;
}

void handleDisplay() {
  if (server.method() != HTTP_POST) {
    server.send(405, "application/json", "{\"error\":\"use POST\"}");
    return;
  }
  JsonDocument doc;
  DeserializationError err = deserializeJson(doc, server.arg("plain"));
  if (err) {
    server.send(400, "application/json", "{\"error\":\"bad json\"}");
    return;
  }

  String flight = doc["flight"] | "";
  currentIcon = doc["icon"] | "";
  lineAirline = doc["airline"] | "";
  lineMake = doc["make"] | "";
  lineModelShort = doc["modelShort"] | "";
  String originCode = doc["originCode"] | "";
  String destCode = doc["destCode"] | "";
  String originCity = doc["originCity"] | "";
  String destCity = doc["destCity"] | "";
  long altitudeFt = doc["altitudeFt"] | -1;

  lineFlightAlt = flight;
  if (altitudeFt >= 0) {
    if (lineFlightAlt.length()) lineFlightAlt += "   ";
    lineFlightAlt += String(altitudeFt) + "ft";
  }

  lineIata = (originCode.length() && destCode.length()) ? (originCode + ">" + destCode) : "";
  lineCity = (originCity.length() && destCity.length()) ? (originCity + " -> " + destCity) : "";

  if (lineAirline.length() == 0 && lineFlightAlt.length() == 0 && lineCity.length() == 0) {
    lineFlightAlt = flight; // fallback if the payload was nearly empty
  }

  resetAllScrollPositions();
  server.send(200, "application/json", "{\"ok\":true}");
}

void handleClear() {
  currentIcon = "";
  lineAirline = "";
  lineFlightAlt = "";
  lineMake = "";
  lineModelShort = "";
  lineIata = "";
  lineCity = "";
  canvas.fillScreen(0);
  dma_display->flipDMABuffer();
  delay(1000 / dma_display->calculated_refresh_rate);
  dma_display->drawRGBBitmap(0, 0, canvas.getBuffer(), PANEL_RES_X, PANEL_RES_Y);
  server.send(200, "application/json", "{\"ok\":true}");
}

// Serves the exact same frame currently drawn into `canvas` as a BMP --
// open http://<board-ip>/debug/screenshot.bmp in a browser to see exactly
// what's on the panel, no photographing needed.
void handleScreenshot() {
  const int w = PANEL_RES_X, h = PANEL_RES_Y;
  const int rowBytes = w * 3; // 24bpp, no padding needed since 64*3=192 is a multiple of 4
  const int pixelDataSize = rowBytes * h;
  const int fileSize = 54 + pixelDataSize;

  uint8_t *bmp = (uint8_t *)malloc(fileSize);
  if (!bmp) {
    server.send(500, "text/plain", "out of memory");
    return;
  }

  auto putLE16 = [](uint8_t *p, uint16_t v) { p[0] = v & 0xFF; p[1] = (v >> 8) & 0xFF; };
  auto putLE32 = [](uint8_t *p, uint32_t v) {
    p[0] = v & 0xFF; p[1] = (v >> 8) & 0xFF; p[2] = (v >> 16) & 0xFF; p[3] = (v >> 24) & 0xFF;
  };

  memset(bmp, 0, 54);
  bmp[0] = 'B'; bmp[1] = 'M';
  putLE32(bmp + 2, fileSize);
  putLE32(bmp + 10, 54); // pixel data offset
  putLE32(bmp + 14, 40); // DIB header size
  putLE32(bmp + 18, w);
  putLE32(bmp + 22, h); // positive height = bottom-up row order
  putLE16(bmp + 26, 1); // planes
  putLE16(bmp + 28, 24); // bits per pixel
  putLE32(bmp + 34, pixelDataSize);

  uint16_t *src = canvas.getBuffer();
  uint8_t *px = bmp + 54;
  for (int y = h - 1; y >= 0; y--) { // BMP rows are stored bottom-up
    for (int x = 0; x < w; x++) {
      uint16_t c = src[y * w + x];
      uint8_t r = ((c >> 11) & 0x1F) * 255 / 31;
      uint8_t g = ((c >> 5) & 0x3F) * 255 / 63;
      uint8_t b = (c & 0x1F) * 255 / 31;
      *px++ = b; *px++ = g; *px++ = r; // BMP is BGR
    }
  }

  server.sendHeader("Content-Type", "image/bmp");
  server.setContentLength(fileSize);
  server.send(200);
  server.sendContent((const char *)bmp, fileSize);
  free(bmp);
}

void setupServer() {
  server.on("/api/display", HTTP_POST, handleDisplay);
  server.on("/api/clear", HTTP_POST, handleClear);
  server.on("/debug/screenshot.bmp", HTTP_GET, handleScreenshot);
  server.begin();
}

void setup() {
  Serial.begin(115200);
  setupSD();     // must finish before setupMatrix() -- SD access after the
                 // HUB75 DMA display starts is unreliable on this board.
  setupMatrix();
  setupWiFi();
  setupNTP();
  setupServer();
}

// Draws `text` statically at `staticX` if it fits within `availWidth`;
// otherwise scrolls it across the full panel width using `scrollX`.
void drawScrollIfNeeded(const String &text, int y, int staticX, int availWidth, int &scrollX) {
  if (text.length() == 0) return;
  int textWidthPx = text.length() * 6;
  if (textWidthPx <= availWidth) {
    canvas.setCursor(staticX, y);
    canvas.print(text);
  } else {
    canvas.setCursor(scrollX, y);
    canvas.print(text);
    scrollX--;
    if (scrollX < -textWidthPx) scrollX = PANEL_RES_X;
  }
}

// Same idea as drawScrollIfNeeded(), but for the beside-icon column: text
// is drawn into rightColCanvas (exactly RIGHT_COL_AVAIL px wide) first,
// then blitted at (mainX, mainY) -- so a long scrolling name is clipped to
// the column and never overdraws the icon to its left.
void drawScrollClipped(const String &text, int mainX, int mainY, int availWidth, int &scrollX) {
  if (text.length() == 0) return;
  int textWidthPx = text.length() * 6;
  rightColCanvas.fillScreen(0);
  rightColCanvas.setTextSize(1);
  rightColCanvas.setTextWrap(false);
  rightColCanvas.setTextColor(textColor);
  if (textWidthPx <= availWidth) {
    rightColCanvas.setCursor(0, 0);
    rightColCanvas.print(text);
  } else {
    rightColCanvas.setCursor(scrollX, 0);
    rightColCanvas.print(text);
    scrollX--;
    if (scrollX < -textWidthPx) scrollX = availWidth;
  }
  canvas.drawRGBBitmap(mainX, mainY, rightColCanvas.getBuffer(), availWidth, 8);
}

void drawAircraft() {
  canvas.fillScreen(0);
  canvas.setTextSize(1);
  canvas.setTextWrap(false);
  canvas.setTextColor(textColor);

  drawScrollIfNeeded(lineAirline, AIRLINE_Y, 1, FULL_WIDTH_AVAIL, scrollXAirline);
  drawScrollIfNeeded(lineFlightAlt, FLIGHTALT_Y, 1, FULL_WIDTH_AVAIL, scrollXFlightAlt);

  uint16_t *iconBuf = findIcon(currentIcon);
  if (iconBuf) {
    canvas.drawRGBBitmap(ICON_X, ICON_Y, iconBuf, ICON_SIZE, ICON_SIZE);
  }
  drawScrollClipped(lineMake, RIGHT_COL_X, MAKE_Y, RIGHT_COL_AVAIL, scrollXMake);
  drawScrollClipped(lineModelShort, RIGHT_COL_X, MODELSHORT_Y, RIGHT_COL_AVAIL, scrollXModelShort);

  drawScrollIfNeeded(lineIata, IATA_Y, 1, FULL_WIDTH_AVAIL, scrollXIata);

  // City names always scroll -- full airport names routinely exceed 64px
  // even alone, so there's no meaningful "fits statically" case here.
  if (lineCity.length()) {
    canvas.setCursor(scrollXCity, CITY_Y);
    canvas.print(lineCity);
    scrollXCity--;
    if (scrollXCity < -(int)(lineCity.length() * 6)) scrollXCity = PANEL_RES_X;
  }
}

// Idle screen shown whenever there's no aircraft payload loaded (i.e. after
// /api/clear, or before the first /api/display). NTP sync runs in the
// background from setupNTP(); until getLocalTime() first succeeds, this
// just shows "SYNCING..." instead of a wrong/zeroed time.
void drawClock() {
  canvas.fillScreen(0);
  canvas.setTextWrap(false);
  canvas.setTextColor(textColor);

  struct tm timeinfo;
  if (!getLocalTime(&timeinfo, 100)) {
    canvas.setTextSize(1);
    canvas.setCursor(4, 28);
    canvas.print("SYNCING...");
    return;
  }

  char timeBuf[6];
  snprintf(timeBuf, sizeof(timeBuf), "%02d:%02d", timeinfo.tm_hour, timeinfo.tm_min);
  canvas.setTextSize(2);
  int timeWidthPx = 5 * 12; // "HH:MM" = 5 chars * 12px/char at size 2
  canvas.setCursor((PANEL_RES_X - timeWidthPx) / 2, 24);
  canvas.print(timeBuf);

  char dateBuf[12];
  snprintf(dateBuf, sizeof(dateBuf), "%02d/%02d/%04d", timeinfo.tm_mday, timeinfo.tm_mon + 1, timeinfo.tm_year + 1900);
  canvas.setTextSize(1);
  int dateWidthPx = strlen(dateBuf) * 6;
  canvas.setCursor((PANEL_RES_X - dateWidthPx) / 2, 44);
  canvas.print(dateBuf);
}

void loop() {
  server.handleClient();

  bool haveContent = lineAirline.length() || lineFlightAlt.length() || lineMake.length() ||
                      lineModelShort.length() || lineIata.length() || lineCity.length();

  unsigned long now = millis();
  if (haveContent) {
    if (now - lastScroll < 25) return; // ~40 updates/sec, needed for smooth scrolling
    lastScroll = now;
    drawAircraft();
  } else {
    if (now - lastScroll < 500) return; // clock only needs to redraw once/sec
    lastScroll = now;
    drawClock();
  }

  // Flip to the back buffer, wait for the swap to take visual effect (see
  // matrix64/02_http_display for why), then blit the freshly-drawn canvas.
  dma_display->flipDMABuffer();
  delay(1000 / dma_display->calculated_refresh_rate);
  dma_display->drawRGBBitmap(0, 0, canvas.getBuffer(), PANEL_RES_X, PANEL_RES_Y);
}
