// Aircraft Overhead Display -- production firmware for the Waveshare
// ESP32-S3-RGB-Matrix board driving a 64x64 HUB75 panel.
//
// Only run this AFTER the WiFi HTTP Text Display firmware
// (matrix64/02_http_display) is confirmed working -- same panel config,
// same double-buffer/flip pattern, this just adds SD icon loading and a
// richer JSON payload/layout on top.
//
// SD card handling: Waveshare's own 05_AnimatedGIFPanel_SD example flags
// (in a code comment) that the TF card becomes unreliable once the HUB75
// DMA display is running. So instead of reading icon files from SD on
// each request, every icon under /icons on the SD card is preloaded into
// PSRAM once at boot, BEFORE the matrix DMA starts -- the SD card is never
// touched again after setup(). SD card must be FAT32.
//
// Icon files: 24x24 raw RGB565, no header, 1152 bytes each, named
// <name>.bin (e.g. /icons/sq_logo.bin) -- generated by:
//   python3 tools/convert_tiles.py --input logos/ --size 24 --format raw565 --output icons
// then copy icons/*.bin to /icons/ on the SD card (not the raw tailfin/
// source images -- those are full-size .webp/.png, not decodable on-device).
//
// Remote icon sync: syncIcons() GETs manifest.json from ICON_BASE_URL (any
// S3-compatible bucket or plain HTTPS host works -- no vendor SDK involved)
// -- a JSON array of {"name", "sha256"} -- and downloads whatever's missing
// or whose hash changed. Runs twice, via the same function with different
// persistToSD:
//   - at boot, right after WiFi connects and before setupMatrix() starts
//     the DMA (SD is still safe to touch): writes new/updated icons to
//     /icons/ AND loads them into PSRAM, so they survive next boot even
//     offline.
//   - periodically from loop() (every ICON_SYNC_INTERVAL_MS): PSRAM only,
//     SD is never touched again once the DMA is running (see note above).
// So a new or updated airline logo shows up within one sync interval with
// no SD card pull required. Build/upload with tools/sync_icons_r2.sh (an
// R2-based reference implementation); see README "Remote icon sync".
// Skipped entirely if ICON_BASE_URL isn't set in secrets.h.
//
// Security: every download goes over TLS validated against ESP32's bundled
// CA root store (setCACertBundle) -- not setInsecure() -- and redirects are
// disabled, so a MITM or malicious proxy can't swap in a fake cert or
// redirect the request elsewhere. On top of that, every downloaded icon's
// SHA-256 is checked against the hash the manifest declared for it (fetched
// over that same validated connection) before it's written anywhere or
// shown on the panel; a mismatch is dropped, not displayed.
//
// Payload from matrix64_aircraft_workflow.json's Build Payload node:
//   {
//     "flight": "SQ123", "airline": "Singapore Airlines",
//     "altitudeFt": 35000,
//     "originCode": "SIN", "destCode": "KUL",
//     "originCity": "Singapore Changi Airport",
//     "destCity": "Kuala Lumpur International Airport",
//     "icon": "sq_logo", "make": "Airbus", "modelShort": "A388"
//   }
//
// Rendering: everything is drawn into an off-screen GFXcanvas16 (same
// draw calls as the real panel -- setCursor/print/drawRGBBitmap all work
// on it identically), then blitted onto the physical display each frame.
// This also means the exact same frame can be served over HTTP as a BMP
// for debugging (see /debug/screenshot.bmp below) instead of needing to
// photograph the panel.
//
// Scroll policy: every line scrolls ONLY if it doesn't fit its available
// width statically (see scrollIfNeeded() below) -- except the city-name
// line, which always scrolls (full airport names routinely exceed 64px
// even alone, so there's no meaningful "fits" case for it).
//
//  y  0- 7: airline name, full width, e.g. "Singapore Airlines"
//  y  8-15: flight number + altitude, full width, e.g. "SQ123   35000ft"
//  y 16-39: icon (24x24, left-aligned) with, to its right:
//             y ~20: make (manufacturer), e.g. "Airbus"
//             y ~30: modelShort (short ICAO type code), e.g. "A320"
//           (airframe age would go here too, but no data source has it --
//           adsbdb's /v0/aircraft/{icao24} has no build-date field)
//  y 41-48: IATA route codes, full width, e.g. "SIN>KUL"
//  y 49-56: origin -> destination city names (ALWAYS scrolling)
//
// Libraries required (Arduino Library Manager):
//   - "ESP32 HUB75 LED MATRIX PANEL DMA Display" by mrfaptastic
//   - "ArduinoJson" by Benoit Blanchon
// (WebServer.h, FS.h, SD_MMC.h all ship with the esp32 core -- no install)
//
// Copy secrets.h.example to secrets.h and fill in your WiFi credentials
// before building -- secrets.h is gitignored, never commit real creds.

#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <WebServer.h>
#include <ArduinoJson.h>
#include <ESP32-HUB75-MatrixPanel-I2S-DMA.h>
#include <Adafruit_GFX.h>
#include <time.h>
#include <mbedtls/sha256.h>
#include "FS.h"
#include "SD_MMC.h"
#include "secrets.h"

// ESP32 Arduino core's built-in trusted-CA bundle (Mozilla's root store,
// baked into the firmware at build time) -- used instead of
// WiFiClientSecure::setInsecure() so icon downloads get real certificate
// validation. Requires arduino-esp32 core >=2.0 (CONFIG_MBEDTLS_CERTIFICATE_BUNDLE,
// on by default); see examples/WiFiClientSecure/BuiltinCertBundle in the core.
extern const uint8_t rootca_crt_bundle_start[] asm("_binary_x509_crt_bundle_start");

// Base URL icons are synced from, e.g. "https://data.airportdata.dev/24x24"
// (no trailing slash -- <base>/manifest.json and <base>/<name>.bin are
// fetched directly). Define in secrets.h to enable syncIcons(); left unset
// here as a no-op default so builds without it configured still compile.
#ifndef ICON_BASE_URL
#define ICON_BASE_URL ""
#endif

// How often loop() re-checks the manifest for new/updated icons while the
// board is running (PSRAM only -- see syncIcons() below for why).
#define ICON_SYNC_INTERVAL_MS (3UL * 24 * 60 * 60 * 1000) // 3 days

// Timezone offset from UTC in seconds (edit per location). Default here is
// SGT (UTC+8) to match the HOME_LAT/HOME_LON in matrix64_aircraft_workflow.json.
#define TIMEZONE_OFFSET_SEC 28800
#define DAYLIGHT_OFFSET_SEC 0

#define PANEL_RES_X 64
#define PANEL_RES_Y 64
#define PANEL_CHAIN 1

// 0 = no rotation, 1 = 90 deg, 2 = 180 deg, 3 = 270 deg
#define DISPLAY_ROTATION 0

// SD_MMC 1-bit GPIO mapping for this exact board, from Waveshare's own
// 05_AnimatedGIFPanel_SD example -- not guessed.
#define BSP_SD_D0  17
#define BSP_SD_CMD 44
#define BSP_SD_CLK 1

#define ICON_SIZE 24
// 319 icons currently ship in icons/ -- MAX_ICONS needs comfortable
// headroom above that so preloadIcons()/syncIcons() don't silently start
// dropping entries as more airlines get added.
#define MAX_ICONS 500

// Layout constants (see header comment above for the row map)
#define AIRLINE_Y 0
#define FLIGHTALT_Y 8
#define ICON_Y 16
#define ICON_X 0
#define RIGHT_COL_X (ICON_SIZE + 2)
#define MAKE_Y (ICON_Y + 4)
#define MODELSHORT_Y (ICON_Y + 14)
#define IATA_Y (ICON_Y + ICON_SIZE + 1)  // 41
#define CITY_Y (IATA_Y + 8)              // 49

#define FULL_WIDTH_AVAIL (PANEL_RES_X - 2)     // full-width rows, 1px margin each side
#define RIGHT_COL_AVAIL (PANEL_RES_X - RIGHT_COL_X - 1) // beside-icon rows

struct IconEntry {
  String name;       // filename without extension, e.g. "sq_logo"
  uint16_t *pixels;  // ICON_SIZE*ICON_SIZE RGB565, PSRAM-allocated
  uint8_t hash[32];  // SHA-256 of the raw pixel bytes -- lets syncIcons()
                      // tell "already have this exact icon" apart from
                      // "have a code by this name but it changed", without
                      // needing to have originally gotten it from the network.
};

IconEntry icons[MAX_ICONS];
int iconCount = 0;

MatrixPanel_I2S_DMA *dma_display = nullptr;
GFXcanvas16 canvas(PANEL_RES_X, PANEL_RES_Y);
// Scratch canvas for the beside-icon column (make/modelShort): scrolling
// long text (e.g. "Avions de Transport Régional" for ATR) is drawn into
// this narrower buffer first, then blitted -- so it can never sweep across
// the icon area the way a full-width scroll would.
GFXcanvas16 rightColCanvas(RIGHT_COL_AVAIL, 8);
WebServer server(80);
uint16_t textColor;

String currentIcon = "";

// Conditionally-scrolling lines: static if they fit their row's available
// width, scroll only if they don't. Each needs its own scrollX so an
// in-progress scroll doesn't reset just because another line redraws.
String lineAirline = "";
String lineFlightAlt = "";
String lineMake = "";
String lineModelShort = "";
String lineIata = "";
int scrollXAirline = PANEL_RES_X;
int scrollXFlightAlt = PANEL_RES_X;
int scrollXMake = PANEL_RES_X;
int scrollXModelShort = PANEL_RES_X;
int scrollXIata = PANEL_RES_X;

// Always-scrolling line (city names)
String lineCity = "";
int scrollXCity = PANEL_RES_X;

unsigned long lastScroll = 0;
unsigned long lastIconSync = 0; // set once at boot; see ICON_SYNC_INTERVAL_MS

int findIconIndex(const String &name) {
  for (int i = 0; i < iconCount; i++) {
    if (icons[i].name == name) return i;
  }
  return -1;
}

uint16_t *findIcon(const String &name) {
  int idx = findIconIndex(name);
  return idx >= 0 ? icons[idx].pixels : nullptr;
}

// Decodes a 64-hex-char string (as manifest.json's "sha256" field) into 32
// raw bytes. Returns false (and leaves out untouched) on malformed input.
bool hexToBytes(const String &hex, uint8_t *out, size_t outLen) {
  if ((size_t)hex.length() != outLen * 2) return false;
  for (size_t i = 0; i < outLen; i++) {
    char byteStr[3] = { hex[2 * i], hex[2 * i + 1], 0 };
    if (!isxdigit((unsigned char)byteStr[0]) || !isxdigit((unsigned char)byteStr[1])) return false;
    out[i] = (uint8_t)strtoul(byteStr, nullptr, 16);
  }
  return true;
}

void preloadIcons() {
  File dir = SD_MMC.open("/icons");
  if (!dir || !dir.isDirectory()) {
    Serial.println("No /icons directory found on SD card -- icons will be blank");
    return;
  }

  const size_t expectedBytes = ICON_SIZE * ICON_SIZE * 2;
  File f = dir.openNextFile();
  while (f && iconCount < MAX_ICONS) {
    if (!f.isDirectory()) {
      String fname = String(f.name());
      int slash = fname.lastIndexOf('/');
      if (slash >= 0) fname = fname.substring(slash + 1);
      if (fname.endsWith(".bin")) {
        if (f.size() == (int)expectedBytes) {
          uint16_t *buf = (uint16_t *)ps_malloc(expectedBytes);
          if (buf) {
            f.read((uint8_t *)buf, expectedBytes);
            icons[iconCount].name = fname.substring(0, fname.length() - 4); // strip ".bin"
            icons[iconCount].pixels = buf;
            mbedtls_sha256((const uint8_t *)buf, expectedBytes, icons[iconCount].hash, 0);
            iconCount++;
          } else {
            Serial.printf("PSRAM alloc failed for %s\n", fname.c_str());
          }
        } else {
          Serial.printf("Skipping %s: %d bytes, expected %d (not a %dx%d raw565 icon)\n",
                         fname.c_str(), (int)f.size(), (int)expectedBytes, ICON_SIZE, ICON_SIZE);
        }
      }
    }
    f = dir.openNextFile();
  }
  Serial.printf("Preloaded %d icons from SD into PSRAM\n", iconCount);
}

// Downloads exactly ICON_SIZE*ICON_SIZE*2 bytes from url into buf and
// checks its SHA-256 against expectedHash before accepting it. TLS is
// validated against the ESP32 core's built-in CA bundle (not
// setInsecure()) and redirects are disabled, so neither a MITM nor a
// compromised proxy can substitute a different host or a different file --
// and even if the origin itself served something unexpected, the hash
// check (computed over the response body, independent of transport) still
// catches it before it's written to SD or shown on the panel.
bool downloadAndVerifyIcon(const String &url, uint16_t *buf, const uint8_t *expectedHash) {
  const size_t expectedBytes = ICON_SIZE * ICON_SIZE * 2;

  WiFiClientSecure client;
  client.setCACertBundle(rootca_crt_bundle_start);
  HTTPClient http;
  http.setTimeout(8000);
  http.setFollowRedirects(HTTPC_DISABLE_FOLLOW_REDIRECTS);
  if (!http.begin(client, url)) return false;

  int code = http.GET();
  if (code != HTTP_CODE_OK || http.getSize() != (int)expectedBytes) {
    Serial.printf("Icon sync: bad response for %s (HTTP %d, %d bytes)\n", url.c_str(), code, http.getSize());
    http.end();
    return false;
  }

  size_t got = http.getStreamPtr()->readBytes((uint8_t *)buf, expectedBytes);
  http.end();
  if (got != expectedBytes) {
    Serial.printf("Icon sync: short read for %s (%d/%d bytes)\n", url.c_str(), (int)got, (int)expectedBytes);
    return false;
  }

  uint8_t actualHash[32];
  mbedtls_sha256((const uint8_t *)buf, expectedBytes, actualHash, 0);
  if (memcmp(actualHash, expectedHash, sizeof(actualHash)) != 0) {
    Serial.printf("Icon sync: hash mismatch for %s -- rejecting (possible tampering or a stale manifest)\n", url.c_str());
    return false;
  }
  return true;
}

// Fetches manifest.json (a JSON array of {"name","sha256"}, e.g.
// [{"name":"sq_logo","sha256":"...64 hex chars..."}, ...]) and downloads
// whichever entries are missing or whose hash doesn't match what's already
// loaded -- covers both "new airline" and "logo art changed" in one pass.
//
// persistToSD must only be true when called before setupMatrix() -- SD
// access is unreliable once the HUB75 DMA display is running (see header
// note), so the periodic call from loop() passes false and updates PSRAM
// only; those updates are re-synced (and then persisted) on the
// next reboot regardless.
void syncIcons(bool persistToSD) {
  if (strlen(ICON_BASE_URL) == 0) {
    Serial.println("Icon sync: ICON_BASE_URL not set, skipping");
    return;
  }

  WiFiClientSecure manifestClient;
  manifestClient.setCACertBundle(rootca_crt_bundle_start);
  HTTPClient http;
  http.setTimeout(8000);
  http.setFollowRedirects(HTTPC_DISABLE_FOLLOW_REDIRECTS);
  if (!http.begin(manifestClient, String(ICON_BASE_URL) + "/manifest.json")) {
    Serial.println("Icon sync: failed to start manifest request");
    return;
  }
  int code = http.GET();
  if (code != HTTP_CODE_OK) {
    Serial.printf("Icon sync: manifest GET failed (HTTP %d)\n", code);
    http.end();
    return;
  }

  JsonDocument manifest;
  DeserializationError err = deserializeJson(manifest, http.getStream());
  http.end();
  if (err) {
    Serial.printf("Icon sync: bad manifest JSON (%s)\n", err.c_str());
    return;
  }

  const size_t expectedBytes = ICON_SIZE * ICON_SIZE * 2;
  int added = 0, updated = 0;
  for (JsonObject entry : manifest.as<JsonArray>()) {
    String name = entry["name"] | "";
    String hashHex = entry["sha256"] | "";
    uint8_t expectedHash[32];
    if (name.length() == 0 || !hexToBytes(hashHex, expectedHash, sizeof(expectedHash))) continue;

    int idx = findIconIndex(name);
    if (idx >= 0 && memcmp(icons[idx].hash, expectedHash, sizeof(expectedHash)) == 0) continue; // up to date
    if (idx < 0 && iconCount >= MAX_ICONS) {
      Serial.println("Icon sync: MAX_ICONS reached, stopping");
      break;
    }

    uint16_t *buf = (uint16_t *)ps_malloc(expectedBytes);
    if (!buf) {
      Serial.printf("Icon sync: PSRAM alloc failed for %s\n", name.c_str());
      continue;
    }
    if (!downloadAndVerifyIcon(String(ICON_BASE_URL) + "/" + name + ".bin", buf, expectedHash)) {
      free(buf);
      continue;
    }

    if (persistToSD) {
      File f = SD_MMC.open("/icons/" + name + ".bin", FILE_WRITE);
      if (f) {
        f.write((uint8_t *)buf, expectedBytes);
        f.close();
      } else {
        Serial.printf("Icon sync: SD write failed for %s (keeping it in PSRAM anyway)\n", name.c_str());
      }
    }

    if (idx >= 0) {
      free(icons[idx].pixels);
      icons[idx].pixels = buf;
      memcpy(icons[idx].hash, expectedHash, sizeof(expectedHash));
      updated++;
      Serial.printf("Icon sync: updated %s\n", name.c_str());
    } else {
      icons[iconCount].name = name;
      icons[iconCount].pixels = buf;
      memcpy(icons[iconCount].hash, expectedHash, sizeof(expectedHash));
      iconCount++;
      added++;
      Serial.printf("Icon sync: added %s\n", name.c_str());
    }
  }

  Serial.printf("Icon sync: %d added, %d updated, %d total\n", added, updated, iconCount);
}

void setupSD() {
  if (!SD_MMC.setPins(BSP_SD_CLK, BSP_SD_CMD, BSP_SD_D0)) {
    Serial.println("SD_MMC setPins failed");
    return;
  }
  if (!SD_MMC.begin("/sdcard", true)) {
    Serial.println("SD card mount failed (is it FAT32?)");
    return;
  }
  if (SD_MMC.cardType() == CARD_NONE) {
    Serial.println("No SD card detected");
    return;
  }
  preloadIcons();
}

void setupMatrix() {
  HUB75_I2S_CFG mxconfig(PANEL_RES_X, PANEL_RES_Y, PANEL_CHAIN);
  // Confirmed working config for this board+panel -- see matrix64/02_http_display
  // for how this was arrived at (gpio.e is the row-address line; without it,
  // content straddling the row-32 boundary splits into two bands).
  mxconfig.gpio.e = 9;
  mxconfig.clkphase = false;
  mxconfig.driver = HUB75_I2S_CFG::FM6126A;
  mxconfig.double_buff = true;

  dma_display = new MatrixPanel_I2S_DMA(mxconfig);
  dma_display->begin();
  dma_display->setRotation(DISPLAY_ROTATION);
  dma_display->setBrightness8(60);
  dma_display->clearScreen();
  textColor = 0xFFFF; // white, RGB565
}

void setupWiFi() {
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.printf("Connecting to %s", WIFI_SSID);
  while (WiFi.status() != WL_CONNECTED) {
    delay(300);
    Serial.print(".");
  }
  Serial.printf("\nConnected. IP: %s\n", WiFi.localIP().toString().c_str());

  lineCity = "READY " + WiFi.localIP().toString();
  scrollXCity = PANEL_RES_X;
}

// Called once at boot, after WiFi is up. NTP sync happens in the background;
// the clock screen (drawClock) just shows "SYNCING..." until getLocalTime()
// first succeeds, so we don't need to block setup() waiting for it.
void setupNTP() {
  configTime(TIMEZONE_OFFSET_SEC, DAYLIGHT_OFFSET_SEC, "pool.ntp.org", "time.nist.gov");
  Serial.println("NTP configured");
}

void resetAllScrollPositions() {
  scrollXAirline = PANEL_RES_X;
  scrollXFlightAlt = PANEL_RES_X;
  // These two scroll within the narrower rightColCanvas, not the full
  // panel, so they should re-enter from just off ITS right edge.
  scrollXMake = RIGHT_COL_AVAIL;
  scrollXModelShort = RIGHT_COL_AVAIL;
  scrollXIata = PANEL_RES_X;
  scrollXCity = PANEL_RES_X;
}

void handleDisplay() {
  if (server.method() != HTTP_POST) {
    server.send(405, "application/json", "{\"error\":\"use POST\"}");
    return;
  }
  JsonDocument doc;
  DeserializationError err = deserializeJson(doc, server.arg("plain"));
  if (err) {
    server.send(400, "application/json", "{\"error\":\"bad json\"}");
    return;
  }

  String flight = doc["flight"] | "";
  currentIcon = doc["icon"] | "";
  lineAirline = doc["airline"] | "";
  lineMake = doc["make"] | "";
  lineModelShort = doc["modelShort"] | "";
  String originCode = doc["originCode"] | "";
  String destCode = doc["destCode"] | "";
  String originCity = doc["originCity"] | "";
  String destCity = doc["destCity"] | "";
  long altitudeFt = doc["altitudeFt"] | -1;

  lineFlightAlt = flight;
  if (altitudeFt >= 0) {
    if (lineFlightAlt.length()) lineFlightAlt += "   ";
    lineFlightAlt += String(altitudeFt) + "ft";
  }

  lineIata = (originCode.length() && destCode.length()) ? (originCode + ">" + destCode) : "";
  lineCity = (originCity.length() && destCity.length()) ? (originCity + " -> " + destCity) : "";

  if (lineAirline.length() == 0 && lineFlightAlt.length() == 0 && lineCity.length() == 0) {
    lineFlightAlt = flight; // fallback if the payload was nearly empty
  }

  resetAllScrollPositions();
  server.send(200, "application/json", "{\"ok\":true}");
}

void handleClear() {
  currentIcon = "";
  lineAirline = "";
  lineFlightAlt = "";
  lineMake = "";
  lineModelShort = "";
  lineIata = "";
  lineCity = "";
  canvas.fillScreen(0);
  dma_display->flipDMABuffer();
  delay(1000 / dma_display->calculated_refresh_rate);
  dma_display->drawRGBBitmap(0, 0, canvas.getBuffer(), PANEL_RES_X, PANEL_RES_Y);
  server.send(200, "application/json", "{\"ok\":true}");
}

// Serves the exact same frame currently drawn into `canvas` as a BMP --
// open http://<board-ip>/debug/screenshot.bmp in a browser to see exactly
// what's on the panel, no photographing needed.
void handleScreenshot() {
  const int w = PANEL_RES_X, h = PANEL_RES_Y;
  const int rowBytes = w * 3; // 24bpp, no padding needed since 64*3=192 is a multiple of 4
  const int pixelDataSize = rowBytes * h;
  const int fileSize = 54 + pixelDataSize;

  uint8_t *bmp = (uint8_t *)malloc(fileSize);
  if (!bmp) {
    server.send(500, "text/plain", "out of memory");
    return;
  }

  auto putLE16 = [](uint8_t *p, uint16_t v) { p[0] = v & 0xFF; p[1] = (v >> 8) & 0xFF; };
  auto putLE32 = [](uint8_t *p, uint32_t v) {
    p[0] = v & 0xFF; p[1] = (v >> 8) & 0xFF; p[2] = (v >> 16) & 0xFF; p[3] = (v >> 24) & 0xFF;
  };

  memset(bmp, 0, 54);
  bmp[0] = 'B'; bmp[1] = 'M';
  putLE32(bmp + 2, fileSize);
  putLE32(bmp + 10, 54); // pixel data offset
  putLE32(bmp + 14, 40); // DIB header size
  putLE32(bmp + 18, w);
  putLE32(bmp + 22, h); // positive height = bottom-up row order
  putLE16(bmp + 26, 1); // planes
  putLE16(bmp + 28, 24); // bits per pixel
  putLE32(bmp + 34, pixelDataSize);

  uint16_t *src = canvas.getBuffer();
  uint8_t *px = bmp + 54;
  for (int y = h - 1; y >= 0; y--) { // BMP rows are stored bottom-up
    for (int x = 0; x < w; x++) {
      uint16_t c = src[y * w + x];
      uint8_t r = ((c >> 11) & 0x1F) * 255 / 31;
      uint8_t g = ((c >> 5) & 0x3F) * 255 / 63;
      uint8_t b = (c & 0x1F) * 255 / 31;
      *px++ = b; *px++ = g; *px++ = r; // BMP is BGR
    }
  }

  server.sendHeader("Content-Type", "image/bmp");
  server.setContentLength(fileSize);
  server.send(200);
  server.sendContent((const char *)bmp, fileSize);
  free(bmp);
}

void setupServer() {
  server.on("/api/display", HTTP_POST, handleDisplay);
  server.on("/api/clear", HTTP_POST, handleClear);
  server.on("/debug/screenshot.bmp", HTTP_GET, handleScreenshot);
  server.begin();
}

void setup() {
  Serial.begin(115200);
  setupSD();             // must finish before setupMatrix() -- SD access
                          // after the HUB75 DMA display starts is unreliable
                          // on this board.
  setupWiFi();            // needed before the icon sync below; also fine to
                          // run before setupMatrix() since WiFi doesn't
                          // touch SD or the panel.
  syncIcons(true);        // last chance to touch SD before DMA starts
  lastIconSync = millis(); // next periodic check is ICON_SYNC_INTERVAL_MS from now
  setupMatrix();
  setupNTP();
  setupServer();
}

// Draws `text` statically at `staticX` if it fits within `availWidth`;
// otherwise scrolls it across the full panel width using `scrollX`.
void drawScrollIfNeeded(const String &text, int y, int staticX, int availWidth, int &scrollX) {
  if (text.length() == 0) return;
  int textWidthPx = text.length() * 6;
  if (textWidthPx <= availWidth) {
    canvas.setCursor(staticX, y);
    canvas.print(text);
  } else {
    canvas.setCursor(scrollX, y);
    canvas.print(text);
    scrollX--;
    if (scrollX < -textWidthPx) scrollX = PANEL_RES_X;
  }
}

// Same idea as drawScrollIfNeeded(), but for the beside-icon column: text
// is drawn into rightColCanvas (exactly RIGHT_COL_AVAIL px wide) first,
// then blitted at (mainX, mainY) -- so a long scrolling name is clipped to
// the column and never overdraws the icon to its left.
void drawScrollClipped(const String &text, int mainX, int mainY, int availWidth, int &scrollX) {
  if (text.length() == 0) return;
  int textWidthPx = text.length() * 6;
  rightColCanvas.fillScreen(0);
  rightColCanvas.setTextSize(1);
  rightColCanvas.setTextWrap(false);
  rightColCanvas.setTextColor(textColor);
  if (textWidthPx <= availWidth) {
    rightColCanvas.setCursor(0, 0);
    rightColCanvas.print(text);
  } else {
    rightColCanvas.setCursor(scrollX, 0);
    rightColCanvas.print(text);
    scrollX--;
    if (scrollX < -textWidthPx) scrollX = availWidth;
  }
  canvas.drawRGBBitmap(mainX, mainY, rightColCanvas.getBuffer(), availWidth, 8);
}

void drawAircraft() {
  canvas.fillScreen(0);
  canvas.setTextSize(1);
  canvas.setTextWrap(false);
  canvas.setTextColor(textColor);

  drawScrollIfNeeded(lineAirline, AIRLINE_Y, 1, FULL_WIDTH_AVAIL, scrollXAirline);
  drawScrollIfNeeded(lineFlightAlt, FLIGHTALT_Y, 1, FULL_WIDTH_AVAIL, scrollXFlightAlt);

  uint16_t *iconBuf = findIcon(currentIcon);
  if (iconBuf) {
    canvas.drawRGBBitmap(ICON_X, ICON_Y, iconBuf, ICON_SIZE, ICON_SIZE);
  }
  drawScrollClipped(lineMake, RIGHT_COL_X, MAKE_Y, RIGHT_COL_AVAIL, scrollXMake);
  drawScrollClipped(lineModelShort, RIGHT_COL_X, MODELSHORT_Y, RIGHT_COL_AVAIL, scrollXModelShort);

  drawScrollIfNeeded(lineIata, IATA_Y, 1, FULL_WIDTH_AVAIL, scrollXIata);

  // City names always scroll -- full airport names routinely exceed 64px
  // even alone, so there's no meaningful "fits statically" case here.
  if (lineCity.length()) {
    canvas.setCursor(scrollXCity, CITY_Y);
    canvas.print(lineCity);
    scrollXCity--;
    if (scrollXCity < -(int)(lineCity.length() * 6)) scrollXCity = PANEL_RES_X;
  }
}

// Idle screen shown whenever there's no aircraft payload loaded (i.e. after
// /api/clear, or before the first /api/display). NTP sync runs in the
// background from setupNTP(); until getLocalTime() first succeeds, this
// just shows "SYNCING..." instead of a wrong/zeroed time.
void drawClock() {
  canvas.fillScreen(0);
  canvas.setTextWrap(false);
  canvas.setTextColor(textColor);

  struct tm timeinfo;
  if (!getLocalTime(&timeinfo, 100)) {
    canvas.setTextSize(1);
    canvas.setCursor(4, 28);
    canvas.print("SYNCING...");
    return;
  }

  char timeBuf[6];
  snprintf(timeBuf, sizeof(timeBuf), "%02d:%02d", timeinfo.tm_hour, timeinfo.tm_min);
  canvas.setTextSize(2);
  int timeWidthPx = 5 * 12; // "HH:MM" = 5 chars * 12px/char at size 2
  canvas.setCursor((PANEL_RES_X - timeWidthPx) / 2, 24);
  canvas.print(timeBuf);

  char dateBuf[12];
  snprintf(dateBuf, sizeof(dateBuf), "%02d/%02d/%04d", timeinfo.tm_mday, timeinfo.tm_mon + 1, timeinfo.tm_year + 1900);
  canvas.setTextSize(1);
  int dateWidthPx = strlen(dateBuf) * 6;
  canvas.setCursor((PANEL_RES_X - dateWidthPx) / 2, 44);
  canvas.print(dateBuf);
}

void loop() {
  server.handleClient();

  // Cast to unsigned long makes this subtraction wrap correctly even across
  // a millis() rollover (~49 days), so this doesn't need its own overflow
  // handling. PSRAM-only (persistToSD=false): the HUB75 DMA is running by
  // now, so SD is off-limits until the next reboot re-syncs it there too.
  if ((unsigned long)(millis() - lastIconSync) >= ICON_SYNC_INTERVAL_MS) {
    lastIconSync = millis();
    syncIcons(false);
  }

  bool haveContent = lineAirline.length() || lineFlightAlt.length() || lineMake.length() ||
                      lineModelShort.length() || lineIata.length() || lineCity.length();

  unsigned long now = millis();
  if (haveContent) {
    if (now - lastScroll < 25) return; // ~40 updates/sec, needed for smooth scrolling
    lastScroll = now;
    drawAircraft();
  } else {
    if (now - lastScroll < 500) return; // clock only needs to redraw once/sec
    lastScroll = now;
    drawClock();
  }

  // Flip to the back buffer, wait for the swap to take visual effect (see
  // matrix64/02_http_display for why), then blit the freshly-drawn canvas.
  dma_display->flipDMABuffer();
  delay(1000 / dma_display->calculated_refresh_rate);
  dma_display->drawRGBBitmap(0, 0, canvas.getBuffer(), PANEL_RES_X, PANEL_RES_Y);
}
